### ISSUE TITLE
Feeds Don’t Load on iPad

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [bobbyearl/traffic-src#2]
I can’t get the feeds to load on an iPad. I know you said Flash, but surely there must be some way for them to load on an iOS. Also, there should be an earlier breaking point for smaller screens cause if it did load, it would be too small to see (see screenshot below). Wondering if you can reduce the white space too, so the videos use more of the screen space (like in V1). Overall, love the design and documentation so far. Very easy to navigate! 
![79258102-b2d8-422a-9ec4-c3b597f6fc68](https://user-images.githubusercontent.com/11530192/34565805-3dfc1e20-f12a-11e7-9314-2c332bd032c2.jpeg)

**Comment by Blackbaud-LindseyRix** [comment]
Forgot to mention, I’m on an iPad Pro 10.5” tablet. iOS 11.2.1

**Comment by bobbyearl** [comment]
I think you'll have to buy me an iPad to test with.  J/K :-) . Thanks for reporting.  I'll see if I can figure it out.

**Comment by bobbyearl** [comment]
Resolved.  Thanks!

**Comment by Blackbaud-LindseyRix** [comment]
I saw this morning, 🎉 !!!! YAY, thank you! Going to use this if we have to leave.
