### ISSUE TITLE
Cameras moved?

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [bobbyearl/traffic-src#63]
I'm seeing some cameras labeled as Wando, but don't look like Wando bridge:

Camera 80005
Camera 80004
The one says Catawba bridge. I'm wondering if SCDOT changed up some cameras.

Also, the cameras that say they are on 41, if i click on them, I think they say they are on 26.

**Comment by Blackbaud-LindseyRix** [comment]
I'll dig into the code to see if I can make a contribution, but wanted to let you know first.

**Comment by bobbyearl** [comment]
Updated to the latest version of the cameras.  Thanks @Blackbaud-LindseyRix!

**Comment by Blackbaud-LindseyRix** [comment]
Sorry I didn't get to a contribution sooner, but happy to see them updated. Will continue to be a loyal fan! :)
